# Site settings
title: John L. Ray
email: johnlray@ucla.edu
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://johnlray.github.io" # the base hostname & protocol for your site
twitter_username: johnlray
github_username: johnlray

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]