name: John Ray's rstats posts
# description: Blogging about stuffs
meta_description: "The posts page from my personal site"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: 
domain_name: 'johnlray.github.io'
gems: [jekyll-paginate]
footer-links:
  github: johnlray
  twitter: johnlray

# Details for the RSS feed generator
url:            'johnlray/github.io'
author:         'John Ray'
