---
title: "Test election tracker"
author: "John Ray"
date: "November 7, 2017"

layout: post

output: 
  md_document:
    variant: markdown_github
---

On this page, I am tracking election results for the State House, State Senate/State Assembly, Governor, and Congressional races going on today.

```{r include=FALSE, warn=FALSE, echo=FALSE}
graphics.off()
rm(list = ls())

library(dplyr)
library(ggplot2)
library(plotly)
library(ggiraph)
library(gridExtra)

load('~/Dropbox/consulting/election_tracker/nightof_data/data_and_graphs.RData')

gov <- read.csv('~/Dropbox/consulting/election_tracker/nightof_data/gov.csv', stringsAsFactors = F)
cd <- read.csv('~/Dropbox/consulting/election_tracker/nightof_data/cd.csv', stringsAsFactors = F)
sh <- read.csv('~/Dropbox/consulting/election_tracker/nightof_data/sh.csv', stringsAsFactors = F)
ss <- read.csv('~/Dropbox/consulting/election_tracker/nightof_data/ss.csv', stringsAsFactors = F)

gov$new_margin = gov$dem2017/(gov$dem2017 + gov$rep2017 + 1)
cd$new_margin = cd$dem2017/(cd$dem2017 + cd$rep2017 + 1)
sh$new_margin = sh$dem2017/(sh$dem2017 + sh$rep2017 + 1)
ss$new_margin = ss$Dem2017/(ss$Dem2017 + ss$Rep2017 + 1)

cd_lines = dplyr::left_join(cd_lines, cd, by = c('STATEFP', 'CD115FP'))
county_df = dplyr::left_join(county_df, gov, by = c('STATEFP','NAME'))
```

```{r echo=FALSE, warn=FALSE}
#gov
gov_gg_new <- ggplot(county_df, aes(x = long, y = lat, group = group, fill = Dem2017, label = County)) +
  geom_polygon() + 
  theme_void() +
  scale_fill_continuous(low = 'red', high = 'darkblue', name = c("Dem %"), labels = scales::percent, limits = c(0, 1)) +
  theme(panel.background = element_rect(color = 'black', fill = NA, size = 1), legend.position = 'bottom') +
  labs(title = 'Governor, 11/7/17')

gov_bar_old <- ggplot(data = gov, aes(x = NAME)) +
  geom_point(aes(y = prev_margin, color = prev_margin), position = 'identity') +
  geom_segment(aes(xend = NAME, y = 0, yend = prev_margin, color = prev_margin)) +
  theme_classic() +
  scale_fill_continuous(low = 'red', high = 'darkblue') +
  labs(y = '', x = '', title = 'Margin by district/county, previous election') +
  scale_y_continuous(labels = scales::percent) +
  theme(panel.background = element_rect(color = 'black', fill = NA, size = 1), legend.position = 'null', axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap(~state)

gov_bar_new <- ggplot(data = gov, aes(x = NAME)) +
  geom_point(aes(y = new_margin, color = new_margin), position = 'identity') +
  geom_segment(aes(xend = NAME, y = 0, yend = new_margin, color = new_margin)) +
  theme_classic() +
  scale_fill_continuous(low = 'red', high = 'darkblue') +
  labs(y = '', x = '', title = 'Margin by district/county, 11/7/17') +
  scale_y_continuous(labels = scales::percent) +
  theme(panel.background = element_rect(color = 'black', fill = NA, size = 1), legend.position = 'null', axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap(~state)

#ss
ss_gg_new <- ggplot(data = ss, aes(xmin = x - .5, xmax = x + .5, ymin = y - .25, ymax = y + .25, fill = new_margin, label = District)) +
  geom_rect_interactive() + 
  theme_void() +
  scale_fill_continuous(low = 'red', high = 'darkblue') +
  labs(title = 'State Senate') +
  theme(panel.background = element_rect(color = 'black', fill = NA, size = 1), legend.position = 'null')

ss_bar_old <- ggplot(data = ss, aes(x = NAME)) +
  geom_point(aes(y = prev_margin, color = prev_margin), position = 'identity') +
  geom_segment(aes(xend = NAME, y = 0, yend = prev_margin, color = prev_margin)) +
  theme_classic() +
  scale_fill_continuous(low = 'red', high = 'darkblue') +
  labs(y = '', x = '') +
  scale_y_continuous(labels = scales::percent) +
  theme(panel.background = element_rect(color = 'black', fill = NA, size = 1), legend.position = 'null', axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap(~state)

ss_bar_new <- ggplot(data = ss, aes(x = NAME)) +
  geom_point(aes(y = new_margin, color = new_margin), position = 'identity') +
  geom_segment(aes(xend = NAME, y = 0, yend = new_margin, color = new_margin)) +
  theme_classic() +
  scale_fill_continuous(low = 'red', high = 'darkblue') +
  labs(y = '', x = '') +
  scale_y_continuous(labels = scales::percent) +
  theme(panel.background = element_rect(color = 'black', fill = NA, size = 1), legend.position = 'null', axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap(~state)

#sh
sh_gg_new <- ggplot(data = sh, aes(xmin = x - .25, xmax = x + .25, ymin = y - .125, ymax = y + .125, fill = new_margin, label = District)) +
  geom_rect() + 
  theme_void() +
  scale_fill_continuous(low = 'red', high = 'darkblue') +
  labs(title = 'State House') +
  theme(panel.background = element_rect(color = 'black', fill = NA, size = 1), legend.position = 'null')

sh_bar_old <- ggplot(data = sh, aes(x = NAME)) +
  geom_point(aes(y = prev_margin, color = prev_margin), position = 'identity') +
  geom_segment(aes(xend = NAME, y = 0, yend = prev_margin, color = prev_margin)) +
  theme_classic() +
  scale_fill_continuous(low = 'red', high = 'darkblue') +
  labs(y = '', x = '') +
  scale_y_continuous(labels = scales::percent) +
  theme(panel.background = element_rect(color = 'black', fill = NA, size = 1), legend.position = 'null', axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap(~state)

sh_bar_new <- ggplot(data = sh, aes(x = NAME)) +
  geom_point(aes(y = new_margin, color = new_margin), position = 'identity') +
    geom_segment(aes(xend = NAME, y = 0, yend = new_margin, color = new_margin)) +
  theme_classic() +
  scale_fill_continuous(low = 'red', high = 'darkblue') +
  labs(y = '', x = '') +
  scale_y_continuous(labels = scales::percent) +
  theme(panel.background = element_rect(color = 'black', fill = NA, size = 1), legend.position = 'null', axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap(~state)

#cong
#house_gg_new <- ggplot(cd_lines, aes(x = long, y = lat, group = group, fill = new_margin, label = District)) +
#  geom_polygon() + 
#  theme_void() +
#  scale_fill_continuous(low = 'red', high = 'darkblue', labels = scales::percent) +
#  theme(panel.background = element_rect(color = 'black', size = 1), legend.position = 'null')

#house_bar_old <- ggplot(data = cd, aes(x = CD115FP)) +
#  geom_point(aes(y = prev_margin, color = prev_margin), position = 'identity') +
#  geom_segment(aes(xend = CD115FP, y = 0, yend = prev_margin, color = prev_margin)) +
#  theme_classic() +
#  scale_color_continuous(low = 'red', high = 'darkblue') +
#  labs(y = '', x = '') +
#  scale_y_continuous(labels = scales::percent) +
#  theme(panel.background = element_rect(color = 'black', size = 1), legend.position = 'null', axis.text.x = element_text(angle = 45, hjust = 1))

#house_bar_new <- ggplot(data = cd, aes(x = CD115FP)) +
#  geom_point(aes(y = new_margin, color = new_margin), position = 'identity') +
#  geom_segment(aes(xend = CD115FP, y = 0, yend = new_margin, color = new_margin)) +
#  theme_classic() +
#  scale_color_continuous(low = 'red', high = 'darkblue') +
#  labs(y = '', x = '') +
#  scale_y_continuous(labels = scales::percent) +
#  theme(panel.background = element_rect(color = 'black', size = 1), legend.position = 'null', axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r echo = FALSE, warning = FALSE}
g1 = grid.arrange(gov_gg_new, sh_gg_new, ss_gg_new, ncol = 3)
ggsave(plot = g1, "~/johnlray.github.io/2017/11/07/figure/unnamed-chunk-3-1.png", height = 5.2, width = 16)
```

```{r echo = FALSE, warning = FALSE}
g2 = grid.arrange(gov_gg, sh_gg, ss_gg, ncol = 3)
ggsave(plot = g2, "~/johnlray.github.io/2017/11/07/figure/unnamed-chunk-4-1.png", height = 5.2, width = 16)
```

```{r echo = FALSE, warning = FALSE}
g3 = grid.arrange(gov_bar_new, sh_bar_new, ss_bar_new, ncol = 3)
ggsave(plot = g3, "~/johnlray.github.io/2017/11/07/figure/unnamed-chunk-5-1.png", height = 5.2, width = 16)
```

```{r echo = FALSE, warning = FALSE}
g4 = grid.arrange(gov_bar_old, sh_bar_old, ss_bar_old, ncol = 3)
ggsave(plot = g4, "~/johnlray.github.io/2017/11/07/figure/unnamed-chunk-6-1.png", height = 5.2, width = 16)
```