---
title: "An R project to learn GIS, ggplot, web scraping, data management, web deployment, and data analysis"
subtitle: "Part 1: R as a GIS"
author: "John Ray"
date: "November 14, 2017"
layout: post

output: html_document
  #md_document:
  #  variant: markdown_github
---

### Introduction to the project

I've been thinking of ways to make a full data course out of one big R project, and the recent [special election in Virginia](https://ballotpedia.org/Virginia_state_legislative_special_elections,_2017) provided just that way. On the day of the election I set up a [dedicated page](https://johnlray.github.io/2017/11/07/election_tracker.html) to gather, format, and plot the results of the election as vote tallies rolled in from the various voting sites across the state. The final version of this project required running one `R` script and committing the subsequent changes to git to update a large dataset gathered from open-source web resources, store and parse it efficiently, generate plots from that data, and then post those plots to the web.

For this project, we will be walking through how to create such a schema. I have chosen to break it down into a few smaller parts so that each unit is a discrete learning lesson on one useful topic. Those topics are:

* Using R as a GIS
* The use of the grammar of graphics with the `ggplot2` library
* Acquiring unruly data from a public resource (webscraping)
* Formatting unruly data
* Deploying data visualizations and analysis to the web
* Conducting statistical analysis
* Putting together the final product

Thus, this post is the first in a series that will have six discrete lessons, and then a seventh to put it all together. My goal with seven lessons is to have a more or less finished product that can take the user from being a novice to being very good with `R` in one week's time. Specifically, I attempt to focus on certain important `R` skills that are common in practice but not taught in many introductory data science courses. Finally, the order of events may seem somewhat strange - ggplot before data storage? - but this series revolves around a real-life project I worked on and, if I could do it over again, this is the order in which I would have assembled the project.

To tie each lesson into the final product, here is how we are going to fit each of these lessons together:

* First, we are going to visualize the geography whose elections we want to track - in this case, Virginia in the 2017 statewide election
* Then, we are going to tinker with our visualization so that it displays our data in an appealing and informative fashion
* We will get some real data from the Virginia Department of Elections to add to our visualizations...
* ...then we will learn how to store that data and format it so its easy to work with
* With our visualizations complete, we will learn how to deploy them to the web using Git and my preferred blogging venue, which is .io with a Jekyll framework
* While this is not a statistical methods project, but a programming project, we will talk through some simple statistical analysis you can conduct in real-ish time, specifically the difference-in-means test
* Finally, we will discuss the full workflow to think about how to optimize our production pipeline

I proceed on the following assumptions:

1. You have `R` and `RStudio` installed on your machine.
2. You are conversant in basic `R` syntax, about what one would know by the end of the excellent [Quick-R tutorials](https://www.statmethods.net/).
3. You are sufficiently conversant in the general political context such that I can say something like "state legislative district" and you know approximately what I'm talking about. Specific knowledge of the Virginia context is not assumed.

That's about it. Let's get started!

### R as a GIS

For this project, we will be plotting legislative districts in the US state of Virginia. Here, we will retrieve spatial data representing these districts from a public resource, load that data into `R`, and plot that data within our RStudio session.

Geographic Information Systems (GIS) is a term that refers generically to any system or program that helps humans interpret and analyze geographic data. Unfortunately, `R` was not designed with GIS in mind. As a result, there are many libraries and approaches to using `R` as a GIS. I present the easiest and most popular way, under the suspicion that the other ways probably won't be updated so much in the future.

This is more than just idle quibbling on my part because the steps needed to make your machine's `R` session into a GIS. Depending on your machine's operating system, `R` will interact with geographic data in a slightly different way. By now, this mostly only manifests in the types of arguments common `R` libraries' functions will take when loading geographic data into your `R` session. Knowing this now diminishes the programming challenge to a mere triviality, but I did not know that loading spatial data into `R` could involve some very fiddly arguments when I was just getting started, and it frustrated me for a long time.

While the quality of American Federalism is such that there is [some disagreement over who lives in what state legislative district](https://wtop.com/virginia/2017/11/147-voted-wrong-house-delegates-race-va/), the US Census maintains the most up-to-date spatial data on legislative districts in the United States [here](https://www.census.gov/geo/maps-data/data/cbf/cbf_sld.html). For this project, we will be using the spatial data representing the lower house, the Virginia House of Delegates, which lives [here](http://www2.census.gov/geo/tiger/GENZ2016/shp/cb_2016_51_sldu_500k.zip). While I typically prefer the fairly friendly point-and-click interface of the Census website to get my data, you can replicate this process by running the following code.

```{r download, echo = FALSE}
download.file('http://www2.census.gov/geo/tiger/GENZ2016/shp/cb_2016_51_sldu_500k.zip', '~/Downloads/cb_2016_51_sldl_500k.zip')
unzip('~/Downloads/cb_2016_51_sldl_500k.zip', exdir = '~/Downloads/cb_2016_51_sldl_500k')
```