---
title: "Ggplot2"
author: "John Ray"
date: "January 22, 2018"
output: html_document
---

In the previous post, we learned how to acquire spatial data and manipulate it in a few basic but important ways in `R`. We did not run much code in the previous post. Indeed, to get up to speed, the only code you need to run is:

```{r last_time, eval = F}
library(rgdal, quietly = T, warn.conflicts = F)
library(ggplot2)

download.file('http://www2.census.gov/geo/tiger/GENZ2016/shp/cb_2016_51_sldl_500k.zip', '~/Downloads/cb_2016_51_sldl_500k.zip')
unzip('~/Downloads/cb_2016_51_sldl_500k.zip', exdir = '~/Downloads/cb_2016_51_sldl_500k')

shp = readOGR('~/Downloads/cb_2016_51_sldl_500k/', layer = 'cb_2016_51_sldl_500k')

ggplot(shp, aes(x = long, y = lat, group = group)) +
  geom_polygon()
```

It may seem odd to have written so little code for what is supposed to be a tutorial! Code tutorials and `R` tutorials are not the same thing, in my view. In this tutorial I will focus on best practices without presenting the false notion there is only one way to things in this language. The best way to do things in `R` is the way you understand, can do quickly, can replicate, and can share with your teammates. There is consensus on a few general practices, and those are what we will focus on.

The domain of data visualization is one with strong general consensus on practice among `R` users. The library `ggplot2` is the modal means of vata visualization. Indeed, you will find many other libraries that contain their own built-in functions for data viz, that will almost always be simply a custom call to `ggplot2`! One reason for this is that `ggplot2` is based on a theory of data visualization that is quite coherent and logical, and even sensible once you get the hang of it. There are a few papers on the underlying concept, one of them being [here](http://www.jstor.org/stable/pdf/25651297.pdf?casa_token=5f5uQwd-ZZcAAAAA:qu40H1YSwBg7mwKx37vs9Rop8gzo5cY0EeWuTq5H6MFOngy-HoiOpYY-Nfy4lV2GvYG1PGRH9CPpv7gm0sWXXJ7aqtXKZhgp67q9ezdxsFcmYJnsxozE), but the general idea is that there is a, you guessed it, **g**rammer of **g**raphics. That grammar is composed of six distinct types. Those types are:

* **data**: The data you want to plot
* **mapping**: Directions that relate the underlying data to the visualization being displayed
* **layers**: The geometric shapes (bars? Points?), statistical transformations (a regression line? A smoother?), and position adjustments (should the bars be next to each other? On top of each other?) that represent the data
* **scales**: How our mappings relate to the plot's aesthetics (are we shading in points based on the party of the legislator? Are we highlighting estimates that are statistically different from one another?)
* **a coordinate system**: What are x and y? How far does each go? What is their scale?
* **a facet speficitation**: How many individual panes we are using to portray our data (does each state get its own plot? Each party? All in one?)

Any object that contains information of all six types is a data visualization. 

Most likely, some of these components of our grammar seem too obvious to state out loud. I often find that when I remind students they need to be explicit that their data visualization is going to contain ``a picture,'' i.e., a facet, the silent look I get in response can be translated as saying, ``no shit, Sherlock.'' Fortunately, `ggplot2` concurs with the apparent deficit of Victorian offal. By default, `ggplot2` will make (pretty good) guesses for the coloration and placement of our layers (the **scales** argument), how far x and y should go (the **coordinate system**), and how many plots to draw (the **facet specification**).

We will start with a simple example and then move on to the data I introduced in the previous episode. A simple example is worth our time because, while the code for a nice ggplot can get fairly complex, the underlying concepts being put into code will always be the same. Lets say we have some data on the air temperatures of two cities, over the course of a year. That data is available [here]().