---
title: "What is the Z-Transformation Doing?"
author: "John Ray"
date: "February 6, 2017"
output: html_document
---

### What is the Z-Transformation Doing?

In the statistics class I teach here at UCLA, I find students are often confused by one of the most important parts of statistics: the Z transformation. From a pedagogical standpoint, this is understandable. I am generally nervous every time I try to teach the Z transformation. Not only did I learn it in a confusing way on my first few passes through statistics, but I have tried several different ways of constructing the concept for my students in a way that will most easily help them encode it into their memories, and I don't feel I've quite cracked it yet.

Here, I try a different approach to presenting the purpose of the Z-transformation: I start at the end and work my way backward. I do this because the ``end'' of the process is the part we can actually understand the most easily, and the previous stuff is almos purely conceptual.

For example, lets start with a question we already know the answer to: Do Democrats and Republicans feel differently about President Trump? The answer, of course, is yes. Not just yes. *OBVIOUSLY, YES!* Before even asking students to sit down and work through some math, I'm presenting them with a problem they already know the answer to.